name: Scrape FED Diario

on:
  schedule:
    - cron: "0 2 * * *" # Cada día a las 2:00 AM UTC
  workflow_dispatch:    # Permite ejecutar el workflow manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar Chrome browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          check-latest: true

      - name: Instalar dependencias del sistema
        run: sudo apt-get update && sudo apt-get install -y libgbm-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Ejercutar scraper
        run: python PARCIAL/fed_scraper.py

      - name: Git Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización automática de tasas FED"
          commit_user_name: "Matiaz Chevez"
          commit_user_email: "matiaz.chevez.c@uni.pe"
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
